SELECT ANIMAL_ID,NAME, 
CASE WHEN SEX_UPON_INTAKE LIKE 'Intact%' THEN 'X'
ELSE 'O' END AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# CASE 컬럼  
#     WHEN 조건1 THEN 값1 
#     WHEN 조건2 THEN 값2 
#     ELSE 값3 
# END 