SELECT F.PRODUCT_ID,F.PRODUCT_NAME,SUM(F.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT F
JOIN FOOD_ORDER O
ON F.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '%2022-05%'
GROUP BY F.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC