# WITH RECURSIVE : 가상 테이블을 생성
WITH RECURSIVE CTE AS (
 SELECT 0 AS HOUR
 UNION ALL
 SELECT HOUR+1 FROM CTE WHERE HOUR<23
)
SELECT CTE.HOUR,COUNT(O.DATETIME) AS COUNT
FROM CTE
LEFT OUTER JOIN ANIMAL_OUTS O
ON CTE.HOUR = HOUR(O.DATETIME)
GROUP BY CTE.HOUR
ORDER BY CTE.HOUR